{% set name = "executorlib" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/executorlib-{{ version }}.tar.gz
  sha256: 1a9efd09e10d8e25c11f5fe65e6f073b4700b0f53d31ec11b1338e42cc3a5250

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - cloudpickle
    - pyzmq
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >=3.9,<3.13
    - cloudpickle >=2.0.0,<=3.1.0
    - pyzmq >=25.0.0,<=26.2.0

test:
  imports:
    - executorlib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  home: https://github.com/pyiron/executorlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
