{% set name = "executorlib" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/executorlib-{{ version }}.tar.gz
  sha256: e76c115f0f94aa069fc845f50d2cc5c3b43fabcdc06a559ca551fda2bcbe3a60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - cloudpickle
    - pyzmq
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }},<3.13
    - cloudpickle >=2.0.0,<=3.1.0
    - pyzmq >=25.0.0,<=26.2.0

test:
  imports:
    - executorlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  home: https://github.com/pyiron/executorlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
