{% set name = "executorlib" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/executorlib-{{ version }}.tar.gz
  sha256: ef2cc0f18eb5327477f0b7784c4c6cecd2c5cafe4ead3587ab1f176d73265037

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - cloudpickle
    - pyzmq
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }}
    - cloudpickle >=2.0.0,<=3.1.1
    - pyzmq >=25.0.0,<=26.2.1

test:
  imports:
    - executorlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  home: https://github.com/pyiron/executorlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
