{% set name = "executorlib" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/executorlib-{{ version }}.tar.gz
  sha256: 21ce830bc9284ec9a45fca019db13ae1cdbfb94a4fa0f616f96f3b36691b7ffd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - cloudpickle
    - pyzmq
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - cloudpickle >=2.0.0,<=3.1.1
    - pyzmq >=25.0.0,<=27.0.0

test:
  imports:
    - executorlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  home: https://github.com/pyiron/executorlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
