{% set name = "executorlib" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/executorlib-{{ version }}.tar.gz
  sha256: 9cd753bbb4d9f9db1464b225289a9b019fe97f94d6a44682da3a62d70fc58b84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - cloudpickle
    - pyzmq
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >=3.9,<3.13
    - cloudpickle >=2.0.0,<=3.0.0
    - pyzmq >=25.0.0,<=26.2.0

test:
  imports:
    - executorlib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  home: https://github.com/pyiron/executorlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
