schema_version: 1

context:
  name: executorlib
  version: "1.7.1"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/executorlib-${{ version }}.tar.gz
  sha256: fe0e9665aa4179d25acd2be7232bf806bbe19069266c49a795143f224c383fd8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - cloudpickle
    - pyzmq
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - cloudpickle >=2.0.0,<=3.1.1
    - pyzmq >=25.0.0,<=27.1.0

tests:
  - python:
      imports:
        - executorlib
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/executorlib

extra:
  recipe-maintainers:
    - jan-janssen
