schema_version: 1

context:
  name: executorlib
  version: 1.6.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/executorlib-${{ version }}.tar.gz
  sha256: eff213d22735072a967de59e33bcb484632f6843113cd9857187a11e01c7af88

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - cloudpickle
    - pyzmq
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - cloudpickle >=2.0.0,<=3.1.1
    - pyzmq >=25.0.0,<=27.0.0

tests:
  - python:
      imports:
        - executorlib
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Scale serial and MPI-parallel python functions over hundreds of compute nodes all from within a jupyter notebook or serial python process.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/executorlib

extra:
  recipe-maintainers:
    - jan-janssen
